name = "افتر دارک"
description = "یک تم مشکی زیبا و ساده برای Zola."
license = "MIT"
homepage = "https://github.com/Thecode764/after-dark"
min_version = "0.17.0"
[extra]


[author]
name = "Thecode764"
homepage = "https://thecode764.github.io"

[original]
author =  "getzola"
repo = "https://git.habd.as/getzola/after-dark/"
